version: '3.6'
services:
  redis:
    restart: unless-stopped
    image: redis:3.2-alpine

  postgres:
    restart: unless-stopped
    image: postgres:9.6-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  memcached:
    restart: unless-stopped
    image: memcached:1.5-alpine

  smtp:
    restart: unless-stopped
    image: tianon/exim4

  sentry-base:
    build: .
    restart: unless-stopped
    env_file:
      - ./common.env
    volumes:
      - ./data/sentry:/var/lib/sentry/files
    ports:
      - '80:9000'

  sentry-cron:
    build: .
    restart: unless-stopped
    env_file:
      - ./common.env
    volumes:
      - ./data/sentry:/var/lib/sentry/files
    command: run cron

  sentry-worker-1:
    build: .
    restart: unless-stopped
    env_file:
      - ./common.env
    volumes:
      - ./data/sentry:/var/lib/sentry/files
    command: run worker
