version: '3.6'
services:
  base:
    build: .
    environment:
      # Run `docker-compose run web config generate-secret-key`
      # to get the SENTRY_SECRET_KEY value.
      # SENTRY_SECRET_KEY: ''
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_EMAIL_HOST: smtp
    volumes:
      - ./data/sentry:/var/lib/sentry/files
    links:
      - redis
      - postgres
    ports:
      - '80:9000'

  redis:
    image: redis:3.2-alpine

  postgres:
    image: postgres:9.6-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  cron:
    extends: base
    command: run cron
    links:
      - redis
      - postgres
      - memcached
      - smtp

  worker:
    extends: base
    command: run worker
    links:
      - redis
      - postgres
      - memcached
      - smtp
